[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn run:app --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT"
healthcheckPath = "/check-auth"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
